apiVersion: v1
kind: Namespace
metadata:
  name: chrome-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chrome-ns
  name: chrome
  labels:
    app: chrome
spec:
  selector:
    matchLabels:
      app: chrome
  replicas: 1
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
        - name: chrome
          image: browserless/chrome
          ports:
            - name: chrome
              containerPort: 3000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: chrome-ns
  name: chrome-svc
spec:
  ports:
    - name: chrome
      targetPort: chrome
      port: 3000
  selector:
    app: chrome
